version: "3"
services:
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
    - "http.host=0.0.0.0"
    - "transport.host=127.0.0.1"
    - "xpack.security.enabled=false"
    ports:
    - "9200:9200"

  redis:
    container_name: redis
    image: redis:6.2.3-alpine3.13
    ports:
      - "6379:6379"

volumes:
  esdata:
    driver: local
